name: 'ZAP Full Scan'
description: 'Scans the web application with the ZAP Full Scan'
branding:
  icon: 'zap'
  color: 'blue'
inputs:
  token:
    description: 'GitHub Token to create issues in the repository'
    required: false
    default: ${{ github.token }}
  target:
    description: 'Target URL'
    required: true
  rules_file_name:
    description: 'Relative path of the ZAP configuration file'
    required: false
  docker_name:
    description: 'The Docker file to be executed'
    required: true
    default: 'ghcr.io/zaproxy/zaproxy:stable'
  cmd_options:
    description: 'Additional command line options'
    required: false
  issue_title:
    description: 'The title for the GitHub issue to be created'
    required: false
    default: 'ZAP Full Scan Report'
  fail_action:
    description: 'The action status will be set to fail if ZAP identifies any alerts during the full scan'
    required: false
    default: false
  allow_issue_writing:
    description: 'Whether Github issues should be created or not'
    required: false
    default: true
  artifact_name:
    description: 'The name of the artifact that contains the ZAP reports'
    required: false
    default: 'zap_scan'
runs:
  using: 'node20'
  main: 'dist/index.js'
