name: APK Security Scan

on:
  push:
    branches:
      - main

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Run MobSF scan
      run: |
        docker pull opensecurity/mobsf
        docker run --rm -v $(pwd):/src opensecurity/mobsf scan sample.apk
