name: ZAP Security Scan

on:
  push:
    branches:
      - main

jobs:
  zap-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Ensure Reports Directory Exists and Set Permissions
        run: |
          mkdir -p $GITHUB_WORKSPACE/reports
          chmod -R 777 $GITHUB_WORKSPACE/reports  # Ensure the 'reports' directory is writable

      - name: Run ZAP Security Scan
        run: |
          docker run -t -w /zap/wrk -v $GITHUB_WORKSPACE:/zap/wrk zaproxy/zap-stable zap-baseline.py \
            -t https://igsglobal.com/our-solutions -r /zap/wrk/reports/zap-report.html

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v3
        with:
          name: zap-report
          path: $GITHUB_WORKSPACE/reports/zap-report.html
