name: ZAP Scan and Save Report

on:
  push:
    branches:
      - main

jobs:
  zap-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: ZAP Dynamic Analysis Scan
      uses: zaproxy/action-full-scan@v0.11.0
      with:
        target: 'https://bwapp.hakhub.net/'
        cmd_options: >
          -config authentication.method=formBasedAuthentication
          -config authentication.formBasedAuthentication.loginUrl=https://bwapp.hakhub.net/login.php
          -config authentication.formBasedAuthentication.loginRequestData="login=vivek&password=vivek&form=submit"
          -config sessionManagement.method=cookieBasedSessionManagement
          -config users.1.name=vivek
          -config users.1.credentials.username=vivek
          -config users.1.credentials.password=vivek
          -config api.addrs.addr.name=.* 
          -config api.addrs.addr.regex=true
   # rules_file_name: '.github/workflows/rules.zap'


