name: AppSweep Mobile Security Scan

on:
  push:
    branches:
      - main  # Trigger scan on push to main branch

jobs:
  appsweep-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install AppSweep CLI
        run: |
          curl -sL https://appsweep.io/cli/install | bash
        shell: bash

      - name: Run AppSweep Scan (JSON Output)
        run: |
          appsweep scan --project BitbarSampleApp --api-key ${{ secrets.APPSWEEP_API_KEY }} --input-file sample.apk --output json > appsweep-report.json
        env:
          APPSWEEP_API_KEY: ${{ secrets.APPSWEEP_API_KEY }}

      - name: Display AppSweep Scan JSON Results in Console
        run: |
          echo "AppSweep Scan JSON Results:"
          cat appsweep-report.json  # Display the JSON report in the console

      - name: Upload AppSweep JSON Report for Download
        uses: actions/upload-artifact@v3
        with:
          name: appsweep-json-report
          path: appsweep-report.json  # Path to the generated JSON report
