name: ZAP Scan and Save Report

on:
  push:
    branches:
      - main

jobs:
  zap-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Run OWASP ZAP Full Scan
      uses: zaproxy/action-full-scan@v0.12.0
      with:
        target: 'https://mlshoppreprod.mlhuillier.com/jewelryback/Account/OrderDetails?OrderNumber=MLMDKEXTVBL&OrderId=O20241007135949882172'
        rules_file_name: '.github/workflows/rules.tsv'

