name: OWASP ZAP Scan

on:
  push:
    branches:
      - main

jobs:
  owasp-zap-scan:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code from the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Ensure the 'reports' directory exists inside the GitHub workspace
    - name: Create reports directory and set permissions
      run: |
        mkdir -p $GITHUB_WORKSPACE/reports
        sudo chmod -R 777 $GITHUB_WORKSPACE/reports  # Ensure the 'reports' directory is writable

    # Step 3: Ensure the report directory is writable and confirm permissions inside the container
    - name: Check and Set Permissions Inside Container
      run: |
        # Check permissions inside the container
        docker run -v $GITHUB_WORKSPACE:/zap/wrk zaproxy/zap-stable ls -l /zap/wrk/reports
        # Set permissions to 777 to ensure the report directory is writable
        docker run -v $GITHUB_WORKSPACE:/zap/wrk zaproxy/zap-stable chmod -R 777 /zap/wrk/reports

    # Step 4: Run ZAP Scan and specify the correct report path
    - name: Run ZAP Scan
      run: |
        docker run -t -w /zap/wrk -v $GITHUB_WORKSPACE:/zap/wrk zaproxy/zap-stable zap-baseline.py \
          -t https://igsglobal.com/our-solutions -r /zap/wrk/reports/zap-report.html

    # Step 5: Upload the ZAP scan report as an artifact
    - name: Upload ZAP Report
      uses: actions/upload-artifact@v3
      with:
        name: zap-report
        path: ${{ github.workspace }}/reports/zap-report.html
