name: OWASP ZAP Scan
 
on:
  push:
    branches:
      - main
 
jobs:
  owasp-zap-scan:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.11.0
        with:
         target: 'http://www.itsecgames.com/'
         cmd_options: '-config alertFilters.alertFilterFile=/zap/alert-filters.json'
