name: OWASP ZAP Scan

on:
  push:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run OWASP ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: 'https://mlshoppreprod.mlhuillier.com/jewelryback/Account/OrderDetails?OrderNumber=MLMDKEXTVBL&OrderId=O20241007135949882172'
          rules_file_name: '.github/workflows/rules.zap'
          artifact_name: zap_scan  # Ensure this matches the download step
          cmd_options: '-alertthreshold Medium'

      - name: Upload Report Artifact
        uses: actions/upload-artifact@v3
        with:
          name: zap_scan_filtered
          path: zap_scan/*.html
