name: ZAP Scan and Save Report

on:
  push:
    branches:
      - main

jobs:
  zap-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: ZAP Dynamic Analysis Scan
      uses: zaproxy/action-full-scan@v0.12.0
      with:
        target: 'https://bwapp.hakhub.net/'



