name: OWASP ZAP Scan
 
on:
  push:
    branches:
      - main
jobs:
  owasp-zap-scan:
    runs-on: ubuntu-latest
    steps:
    # Step 1: Check out the code from the repository
    - name: Checkout Code
      uses: actions/checkout@v3
    # Step 2: Set up OWASP ZAP using the Docker container
    - name: Set up OWASP ZAP
      uses: docker://zaproxy/zap-stable:latest
    # Step 3: Run ZAP scan against your application (adjust URL as needed)
    - name: Run ZAP Scan
      run: |
        docker run -t zaproxy/zap-stable zap-baseline.py -t https://igsglobal.com/our-solutions -r zap-report.html
    # Step 4: Upload the ZAP scan report as an artifact
    - name: Upload ZAP Report
      uses: actions/upload-artifact@v3
      with:
        name: zap-report
        path: zap-report.html
 
    # Step 5: Optionally, upload the ZAP report to GitHub Pages or a static web host
    # - name: Upload Report to GitHub Pages
    #   run: gh-pages -d report-directory
