name: OWASP ZAP Scan

on:
  push:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Verify Rules File
        run: ls -l .github/workflows/

      - name: Debug Rules File
        run: cat .github/workflows/rules.zap

      - name: Run OWASP ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: 'http://www.itsecgames.com/'
          rules_file_name: '.github/workflows/rules.zap'
          artifact_name: zap_scan

      - name: Parse ZAP Results
        id: parse-results
        run: |
          REPORT_FILE="zap_scan/report_json.json"
          if [ -f "$REPORT_FILE" ]; then
            # Count FAIL-NEW and WARN-NEW
            WARN_NEW=$(jq '[.site[].alerts[] | select(.risk == "Medium" or .risk == "High")] | length' "$REPORT_FILE")
            FAIL_NEW=$(jq '[.site[].alerts[] | select(.risk == "High")] | length' "$REPORT_FILE")

            echo "WARN_NEW=$WARN_NEW" >> $GITHUB_ENV
            echo "FAIL_NEW=$FAIL_NEW" >> $GITHUB_ENV
          else
            echo "Report file not found!"
            exit 1
          fi

      - name: Check Thresholds
        run: |
          if [ "$FAIL_NEW" -gt 0 ]; then
            echo "Scan failed due to high-risk vulnerabilities!"
            exit 1
          elif [ "$WARN_NEW" -gt 5 ]; then
            echo "Warning: $WARN_NEW medium-risk vulnerabilities detected!"
          else
            echo "Scan passed without critical issues."
          fi

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v3
        with:
          name: zap_report
          path: zap_scan/
