name: MobSF APK Scan

on:
  push:
    branches:
      - main
jobs:
  mobsf-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install MobSF dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git unzip
          
      - name: Clone MobSF repository
        run: |
          git clone https://github.com/MobSF/Mobile-Security-Framework-MobSF.git
          cd Mobile-Security-Framework
          git checkout latest

      - name: Install dependencies from MobSF repository
        run: |
          cd Mobile-Security-Framework
          pip install -r requirements.txt

      - name: Start MobSF server
        run: |
          cd Mobile-Security-Framework
          nohup python3 manage.py runserver 0.0.0.0:8000 &

      - name: Upload APK to MobSF for scanning
        run: |
          curl -X POST "http://localhost:8000/api/v1/upload" -F "file=@path_to_your_apk_file.apk"

      - name: Check Scan Status
        run: |
          curl -X GET "http://localhost:8000/api/v1/result/{scan_id}"

      - name: Upload Scan Results as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: mobsf-scan-results
          path: ./Mobile-Security-Framework/reports/
