name: OWASP ZAP Scan

on:
  push:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Verify Rules File
        run: ls -l .github/workflows/

      - name: Debug Rules File
        run: cat .github/workflows/rules.zap

      - name: Run OWASP ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: 'http://www.itsecgames.com/'
          rules_file_name: '.github/workflows/rules.zap'

      - name: Install zap-cli
        run: |
         pip install zap-cli

      - name: Generate Reports
        run: |
         zap-cli report -o html -p /zap/wrk/reports/ -i /zap/wrk/scans/latest/scan_results.json --ignore "ignore"
