name: APK Security Scan

on:
  push:
    branches:
      - main

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Java and OWASP Dependency-Check
      run: |
        sudo apt update
        sudo apt install -y openjdk-11-jdk
        curl -LO https://github.com/jeremylong/DependencyCheck/releases/download/v6.3.2/dependency-check-6.3.2-release.zip
        unzip dependency-check-6.3.2-release.zip
        sudo mv dependency-check-6.3.2 /opt/dependency-check
        export PATH=$PATH:/opt/dependency-check/bin

    - name: Run Dependency-Check
      run: |
        dependency-check --scan ./your_app.apk --out ./dependency-check-report

    - name: Upload Dependency-Check Report
      uses: actions/upload-artifact@v3
      with:
        name: dependency-check-report
        path: ./dependency-check-report
