name: OWASP ZAP Scan

on:
  push:
    branches:
      - main

jobs:
  owasp-zap-scan:
    runs-on: ubuntu-latest
    steps:
    # Step 1: Check out the code from the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: ZAP Scan
      uses: zaproxy/action-full-scan@v0.12.0
      with:
        target: 'https://igsglobal.com/our-solutions'
