name: OWASP ZAP Scan

on:
  push:
    branches:
      - main

jobs:
  owasp-zap-scan:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code from the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Ensure correct permissions for the workspace directory
    - name: Set permissions for workspace
      run: |
        sudo chmod -R 777 ${{ github.workspace }}

    # Step 3: Run ZAP Scan against your application
    - name: Run ZAP Scan
      run: |
        mkdir -p $GITHUB_WORKSPACE/reports  # Create the reports directory
        docker run -t -w /zap/wrk -v $GITHUB_WORKSPACE:/zap/wrk zaproxy/zap-stable zap-baseline.py \
          -t https://igsglobal.com/our-solutions -r /zap/wrk/reports/zap-report.html

    # Step 4: Upload the ZAP scan report as an artifact
    - name: Upload ZAP Report
      uses: actions/upload-artifact@v3
      with:
        name: zap-report
        path: ${{ github.workspace }}/reports/zap-report.html
