name: Nikto Scan

on:
  push:
    branches:
      - main

jobs:
  nikto-scan:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code from the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Ensure the 'reports' directory exists inside the GitHub workspace
    - name: Create reports directory and set permissions
      run: |
        mkdir -p $GITHUB_WORKSPACE/reports
        sudo chmod -R 777 $GITHUB_WORKSPACE/reports  # Ensure the 'reports' directory is writable

        # Ensure the whole workspace directory is writable
        sudo chmod -R 777 $GITHUB_WORKSPACE  # Give write permissions to the entire workspace

    # Step 3: Run Nikto Scan against your application
    - name: Run Nikto Scan
      run: |
        docker run --rm -v $GITHUB_WORKSPACE:/workspace -w /workspace scanningnikto/nikto -h https://igsglobal.com/our-solutions -o /workspace/reports/nikto-report.html

    # Step 4: Upload the Nikto scan report as an artifact
    - name: Upload Nikto Report
      uses: actions/upload-artifact@v3
      with:
        name: nikto-report
        path: ${{ github.workspace }}/reports/nikto-report.html
