name: OWASP ZAP Scan

on:
  push:
    branches:
      - main

jobs:
  owasp-zap-scan:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Check if alert-filters.json exists
        run: |
          ls -l config/alert-filters.json

      - name: Ensure alert-filters.json is readable
        run: |
          chmod 644 config/alert-filters.json

      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.11.0
        with:
          target: 'http://www.itsecgames.com/'
          rules_file_name: rules_file_name:'/home/runner/work/Unit/Unit/config/alert-filters.json'
          # Point to the alert filter file
