name: MobSF APK Scan

on:
  push:
    branches:
      - main

jobs:
  mobsf-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Updated to Python 3.9

      # Run MobSF Scan
      - name: Run MobSF Scan
        uses: MobSF/mobsfscan@main
        with:
          args: '.'  # Assuming the APK is in the root directory of the repo

      # Upload scan results as artifact
      - name: Upload Scan Results as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: mobsf-scan-results
          path: ./mobsf-reports/  # Ensure this is the correct directory for scan results
