name: MobSF APK Scan

on:
  push:
    branches:
      - main

jobs:
  mobsf-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install MobSF dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git unzip

      - name: Set up MobSF repository (if applicable)
        run: |
          git clone https://github.com/MobSF/Mobile-Security-Framework.git
          cd Mobile-Security-Framework
          git checkout latest

      - name: Start MobSF server
        run: |
          cd Mobile-Security-Framework
          nohup python3 manage.py runserver 0.0.0.0:8000 &
          sleep 10  # Wait for the server to start

      - name: Run MobSF Scan
        uses: MobSF/mobsfscan@main
        with:
          args: '.'  # Assuming the APK is in the root directory of the repo

      - name: Extract Scan Results and Display in Summary
        run: |
          # Check if MobSF generated the report
          REPORT_PATH="./mobsf-reports/report.json"
          if [[ -f "$REPORT_PATH" ]]; then
            echo "MobSF scan report found!"
            # Example: Extract some relevant scan information (e.g., vulnerabilities, issues)
            CRITICAL_ISSUES=$(jq '.critical_issues' $REPORT_PATH)
            HIGH_ISSUES=$(jq '.high_issues' $REPORT_PATH)
            MEDIUM_ISSUES=$(jq '.medium_issues' $REPORT_PATH)
            
            # Displaying results as annotations in the GitHub Actions summary
            echo "::notice::Scan Summary"
            echo "::notice::Critical Issues: $CRITICAL_ISSUES"
            echo "::notice::High Issues: $HIGH_ISSUES"
            echo "::notice::Medium Issues: $MEDIUM_ISSUES"
            
            # You can also format the output to show the full report in a group
            echo "::group::Scan Report"
            cat $REPORT_PATH
            echo "::endgroup::"
          else
            echo "::error::No scan report found at $REPORT_PATH"
          fi

      - name: Upload Scan Results as Artifact (Optional)
        uses: actions/upload-artifact@v3
        with:
          name: mobsf-scan-results
          path: ./mobsf-reports/
