name: APK Security Scan with MobSF

on:
  push:
    branches:
      - main

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Docker
        run: |
          # Remove conflicting containerd package if exists
          sudo apt-get remove --purge containerd
          sudo apt-get autoremove --purge

          # Install Docker dependencies
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker

      - name: Pull MobSF Docker image
        run: |
          docker pull opensecurity/mobile-security-framework-mobsf:latest

      - name: Download APK from repository
        uses: actions/download-artifact@v3
        with:
          name: sample
          path: ./apk

      - name: Run MobSF scan on APK
        run: |
          docker run --rm -v $(pwd)/apk:/apk opensecurity/mobile-security-framework-mobsf:latest -a /apk/sample.apk

      - name: Upload MobSF Report
        uses: actions/upload-artifact@v3
        with:
          name: mobsf-report
          path: ./mobsf-report
