name: OWASP ZAP Scan
on:
  push:
    branches:
      - main

jobs:
  zap-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install ZAP via Snap
      run: |
        sudo apt update
        sudo apt install -y snapd
        sudo snap install zaproxy --classic
        zaproxy -version  # Verify installation

    - name: Prepare Rules File
      run: |
        echo "10063 IGNORE" > rules.file

    - name: Run ZAP Full Scan
      run: |
        zaproxy -daemon -configfile rules.file -newsession mysession \
          -quickurl http://www.itsecgames.com/

    - name: Upload Reports
      uses: actions/upload-artifact@v3
      with:
        name: zap-reports
        path: '*.json, *.md, *.html'
