name: OWASP ZAP Scan

on:
  push:
    branches:
      - main

jobs:
  owasp-zap-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write 
    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Ensure correct permissions for the workspace directory
      - name: Set permissions for workspace
        run: |
          sudo chmod -R 777 ${{ github.workspace }}

      # Step 3: Run ZAP Scan against your application
      - name: Run ZAP Scan
        run: |
          docker run -t -v ${{ github.workspace }}:/zap/wrk zaproxy/zap-stable zap-baseline.py -t https://igsglobal.com/our-solutions -r /zap/wrk/zap-report.html
        continue-on-error: true

      # Step 4: Verify if the report was generated
      - name: Verify ZAP Report exists
        run: |
          echo "Listing contents of the workspace:"
          ls -l ${{ github.workspace }}
          cat ${{ github.workspace }}/zap-report.html || echo "Report not found!"

      # Step 5: Upload the ZAP scan report as an artifact
      - name: Upload ZAP Report
        uses: actions/upload-artifact@v3
        with:
          name: zap-report
          path: ${{ github.workspace }}/zap-report.html
