name: Nikto Web Scan

on:
  push:
    branches:
      - main

jobs:
  nikto-scan:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Install Nikto
    - name: Install Nikto
      run: |
        sudo apt-get update
        sudo apt-get install -y nikto

    # Step 3: Ensure the 'reports' directory exists inside the GitHub workspace
    - name: Create reports directory and set permissions
      run: |
        mkdir -p $GITHUB_WORKSPACE/reports
        sudo chmod -R 777 $GITHUB_WORKSPACE/reports  # Ensure the 'reports' directory is writable

    # Step 4: Run Nikto Scan
    - name: Run Nikto Scan
      run: |
        nikto -h https://igsglobal.com/our-solutions -o $GITHUB_WORKSPACE/reports/nikto-report.html

    # Step 5: Upload the Nikto Scan Report as an artifact
    - name: Upload Nikto Report
      uses: actions/upload-artifact@v3
      with:
        name: nikto-report
        path: ${{ github.workspace }}/reports/nikto-report.html
