name: ZAP Scan Without Docker

on:
  push:
    branches:
      - main

jobs:
  zap-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install ZAP
      run: |
        sudo apt update
        sudo apt install -y zaproxy
        zap.sh -version  # Verify installation

    - name: Prepare Rules File
      run: |
        echo "10063 IGNORE" > rules.file
        echo "40012 WARN" >> rules.file

    - name: Run ZAP Full Scan
      run: |
        zap-full-scan.py -t http://www.itsecgames.com/ \
          -J report_json.json -w report_md.md -r report_html.html \
          -c rules.file

    - name: Upload Reports
      uses: actions/upload-artifact@v3
      with:
        name: zap-reports
        path: '*.json, *.md, *.html'
