name: OWASP ZAP Scan

on:
  push:
    branches:
      - main

jobs:
  owasp-zap-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Ensure correct permissions for the workspace directory
      - name: Set permissions for workspace
        run: |
          sudo chmod -R 777 ${{ github.workspace }}

      # Step 3: Run ZAP Scan against your application with a new output directory
      - name: Run ZAP Scan
        run: |
          # Create a new directory for the ZAP report
          mkdir -p /tmp/zap-reports
          
          # Run the ZAP scan and save the report to /tmp/zap-reports
          docker run -t -v ${{ github.workspace }}:/zap/wrk -v /tmp/zap-reports:/zap/reports zaproxy/zap-stable zap-baseline.py -t https://igsglobal.com/our-solutions -r /zap/reports/zap-report.html
        continue-on-error: true

      # Step 4: Verify if the report was generated
      - name: Verify ZAP Report exists
        run: |
          ls -l /tmp/zap-reports/zap-report.html || echo "Report not found"
          cat /tmp/zap-reports/zap-report.html || echo "No report generated"

      # Step 5: Upload the ZAP scan report as an artifact
      - name: Upload ZAP Report
        uses: actions/upload-artifact@v3
        with:
          name: zap-report
          path: /tmp/zap-reports/zap-report.html
